name: Build Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The CoreELEC version to build'
        required: true
        default: '21.3-Omega'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make gcc git texinfo gzip squashfs-tools
          sudo apt-get install autoconf automake libtool
      

      - name: Run Build
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          cd /home/runner/work/E900V22C-CoreELEC/E900V22C-CoreELEC
          sh build.sh $VERSION

      - name: Export Image
        uses: actions/upload-artifact@v4
        with:
          name: Image & SHA256
          path: |
            /home/runner/work/E900V22C-CoreELEC/E900V22C-CoreELEC/*.img.gz
            /home/runner/work/E900V22C-CoreELEC/E900V22C-CoreELEC/*.img.gz.sha256
